Fixes issues setting transaction name when state loss occurs.
newrelic/newrelic-node-apollo-server-plugin pull request #69
Opened 2021-02-23 20:55 UTC by michaelgoin

## Proposed Release Notes

* Fixed issue where state loss introduced through another module could result in the plugin causing a query to error while trying to set the transaction name.

## Links

* Fixes: https://github.com/newrelic/newrelic-node-apollo-server-plugin/issues/67

## Details

This does not solve the underlying issue of state loss, which is potentially from the usage of AWS XRay in the linked issue. That is a problem likely outside this plugin.

2021-02-23 21:33 UTC, carlo-808 requested changes

2021-02-23 21:33 UTC, carlo-808 commented on tests/integration/state-loss.test.js
> +  t.test('should should not error when state loss just before sending response', (t) => {
minor: 2 shoulds :)

2021-02-24 20:34 UTC, michaelgoin commented on tests/integration/state-loss.test.js
> +  t.test('should should not error when state loss just before sending response', (t) => {
I'M SERIOUS CARLO IT SHOULD

2021-02-24 20:43 UTC, carlo-808 approved these changes
👍

2021-02-24 20:51 UTC, merged